version: '3.8'

services:
  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: airglow_auth_service
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./auth_service:/app
